### ISSUE TITLE
python3 doesn't need "from itertools import izip"

### ISSUE THREAD

**Issue by ghost** [nschloe/tikzplotlib#20]
Running with python3:

Traceback (most recent call last):
  File "./myfile.py", line 46, in <module>
    from matplotlib2tikz import save as tikz_save
  File "/mnt/mob/docs/repo/relk/org/matplotlib2tikz.py", line 30, in <module>
    from itertools import izip
ImportError: cannot import name izip

**Comment by cnrting** [comment]
python3.7 working：from itertools import zip_longest as zip

**Comment by Varat7v2** [comment]
> python3.7 working：from itertools import zip_longest as zip

It worked for me. Thanks.

**Comment by zcun007** [comment]
Hey, How did you you apply this? I'm having this issue while using replit

**Comment by FriedrichFroebel** [comment]
You should report an issue to *replit* if the latest version still has this issue. The fix is detailed above: Just remove the import and use `zip` instead of `izip`.
