### ISSUE TITLE
Using comma as decimal separator breaks tick labels

### ISSUE THREAD

**Issue by MaxSchambach** [nschloe/tikzplotlib#234]
Using a locale setting that uses a comma as decimal separator (e.g. ``de_DE.UTF-8``) breaks the tick labels as the comma is interpreted as a list seperator. For example:

```python
import locale
locale.setlocale(locale.LC_NUMERIC, "de_DE.UTF-8")

import numpy as np
import matplotlib.pyplot as plt

plt.ticklabel_format(useLocale=True)

x = np.arange(0, 8, 1)
y = np.arange(0, 8, 1)
x, y = np.meshgrid(x, y)
z = x*y / 1000

plt.imshow(z)
plt.colorbar()


from matplotlib2tikz import save as tikz_save
tikz_save('test.tikz')
```

produces ``colorbar style={ytick={0,0.01,0.02,0.03,0.04},yticklabels={0,00,0,01,0,02,0,03,0,04},ylabel={}}``  which results in the plot below.

I think it would be great to use ``\num{}`` of the ``SIunitx`` package to handle all numbers that are to be displayed via latex. One could then also change the global behavior of the displaying style via the packages interface.

EDIT: Also, just leaving out the ``yticklabels`` and letting pgfplots do the rest would be fine too.

![screenshot](https://user-images.githubusercontent.com/28300359/40371635-33112cdc-5de3-11e8-9c3a-8104e788f5d3.jpeg)

**Comment by moritzmuehlbauer** [comment]
You can modify axes.py like: 
```python  
for (tick, ticklabel) in zip(ticks, ticklabels):
        pgfplots_ticks.append(tick)
        # store the label anyway
        label = ticklabel.get_text()
        label = re.sub('(\$\d*),(\d*\$)',r'\1{,}\2',label) # If Ticklabels have locale formatter "," they are escaped
```
