### ISSUE TITLE
Feature request: cleanfigure

### ISSUE THREAD

**Issue by Aikhjarto** [nschloe/tikzplotlib#258]
In matlab2tikz, there is a [`cleanfigure('targetResolution',...)`](https://github.com/matlab2tikz/matlab2tikz/blob/816f8754804cd45d8b41b3adf3ff9709a29cf173/src/cleanfigure.m#L12) command to reduce the number of points in line objects, if individual points are not perceptible at a given resolution/papersize.
Is it possible to have such a function also in matplotlib2tikz?

**Comment by svretina** [comment]
That would be a nice feature indeed.

**Comment by graebe** [comment]
Supporting this request! Would be great!

**Comment by hoehnp** [comment]
@Aikhjarto: Thank you for pointing this out. Obviously I searched with the wrong keywords. Have you done any efforts in this direction?

**Comment by hoehnp** [comment]
I have some successes by implementing the ideas from [stackexchange](https://codereview.stackexchange.com/questions/196104/removing-neighbors-in-a-point-cloud) before doing the plotting. I could share my slightly modified version of this, if desired.

**Comment by theRealSuperMario** [comment]
@hoehnp I think it would not hurt if you could share what you have come up with. Eventually, I think it would be best to "just" reimplement the matlab2tikz cleanfigure command as it gives very good results.
https://github.com/matlab2tikz/matlab2tikz/blob/master/src/cleanfigure.m

However, this probably requires many steps and some discipline. But it might be worth the effort.

**Comment by theRealSuperMario** [comment]
I just made a small example and the results are quite astounding:

The example is a simple line plot
```matlab
addpath ("../matlab2tikz/src")

x = linspace(1, 100, 20);
y = linspace(1, 100, 20);

figure
plot(x, y)
xlim([20, 80])
ylim([20, 80])

matlab2tikz("example1_raw.tikz")

cleanfigure;

matlab2tikz("example1_clean.tikz")
```

The raw tikz file contains 20 points

```latex
% This file was created by matlab2tikz.
%
%The latest updates can be retrieved from
%  http://www.mathworks.com/matlabcentral/fileexchange/22022-matlab2tikz-matlab2tikz
%where you can also make suggestions and rate matlab2tikz.
%
\definecolor{mycolor1}{rgb}{0.00000,0.44700,0.74100}%
%
\begin{tikzpicture}

\begin{axis}[%
width=4.506in,
height=3.554in,
at={(0.756in,0.48in)},
scale only axis,
xmin=20,
xmax=80,
ymin=20,
ymax=80,
axis background/.style={fill=white}
]
\addplot [color=mycolor1, forget plot]
  table[row sep=crcr]{%
1	1\\
6.21052631578947	6.21052631578947\\
11.4210526315789	11.4210526315789\\
16.6315789473684	16.6315789473684\\
21.8421052631579	21.8421052631579\\
27.0526315789474	27.0526315789474\\
32.2631578947368	32.2631578947368\\
37.4736842105263	37.4736842105263\\
42.6842105263158	42.6842105263158\\
47.8947368421053	47.8947368421053\\
53.1052631578947	53.1052631578947\\
58.3157894736842	58.3157894736842\\
63.5263157894737	63.5263157894737\\
68.7368421052632	68.7368421052632\\
73.9473684210526	73.9473684210526\\
79.1578947368421	79.1578947368421\\
84.3684210526316	84.3684210526316\\
89.5789473684211	89.5789473684211\\
94.7894736842105	94.7894736842105\\
100	100\\
};
\end{axis}
\end{tikzpicture}%
```

The clean tikz file contains 2 points

```latex
% This file was created by matlab2tikz.
%
%The latest updates can be retrieved from
%  http://www.mathworks.com/matlabcentral/fileexchange/22022-matlab2tikz-matlab2tikz
%where you can also make suggestions and rate matlab2tikz.
%
\definecolor{mycolor1}{rgb}{0.00000,0.44700,0.74100}%
%
\begin{tikzpicture}

\begin{axis}[%
width=4.506in,
height=3.554in,
at={(0.756in,0.48in)},
scale only axis,
xmin=20,
xmax=80,
ymin=20,
ymax=80,
axis background/.style={fill=white}
]
\addplot [color=mycolor1, forget plot]
  table[row sep=crcr]{%
16.6315789473684	16.6315789473684\\
84.3684210526316	84.3684210526316\\
};
\end{axis}
\end{tikzpicture}%
```

**Comment by theRealSuperMario** [comment]
I allowed myself to just go for it and made very good progress on the cleanfigure feature.
Basically, I translated most of the matplotlib2tikz code into python and added appropriate tests.

It works surprisingly well. See example below and `test_cleanfigure.py` on my [fork](https://github.com/theRealSuperMario/tikzplotlib).

```python
        """test high-level usage for simple example.
        Test is successfull if generated tikz code saves correct amount of lines
        """
        from tikzplotlib import get_tikz_code
        import numpy as np
        from matplotlib import pyplot as plt

        from tikzplotlib import cleanfigure
        x = np.linspace(1, 100, 20)
        y = np.linspace(1, 100, 20)

        with plt.rc_context(rc=RC_PARAMS):
            fig, ax = plt.subplots(1, 1, figsize=(5, 5))
            ax.plot(x, y, linestyle="-", marker="None")
            ax.set_ylim([20, 80])
            ax.set_xlim([20, 80])
            raw = get_tikz_code()

            cleanfigure.cleanfigure(fig, ax)
            clean = get_tikz_code()

            # Use number of lines to test if it worked.
            # the baseline (raw) should have 20 points
            # the clean version (clean) should have 2 points
            # the difference in line numbers should therefore be 2
            numLinesRaw = raw.count("\n")
            numLinesClean = clean.count("\n")
            assert numLinesRaw - numLinesClean == 18
```

There are still some things missing, like handling subplots and 3D plots. I will get those done soon. However, I could need some help finding good test cases that break my code. So if someone want's to help, please try to break my code.

**Comment by theRealSuperMario** [comment]
I think we can close this now @nschloe
