### ISSUE TITLE
Inconsistency in extra_*_parameters

### ISSUE THREAD

**Issue by ngc92** [nschloe/tikzplotlib#266]
The `extra_axis_parameters` and `extra_tikzpicture_parameters` arguments seem to work subtly differently: Whereas axis parameters get added as optional parameters to the \begin{axis}[...] call, the tikzpicture parameters are added as separate lines inside the \begin{tikzpicture} environment. 

Also, is there a way to the two missing combinations? Adding code inside the `axis` environment, and adding optional parameters to the `tikzpicture` environment?

**Comment by LukasDrude** [comment]
I believe this is a bug and not an inconsistency.

The code [here](https://github.com/nschloe/tikzplotlib/blob/master/tikzplotlib/save.py#L215) should read:

```
    if wrap and add_axis_environment:
        code += "\\begin{tikzpicture}"
        if extra_tikzpicture_parameters:
            code += "[\n"
            code += ",\n".join(data["extra tikzpicture parameters"])
            code += "\n]"
        code += "\n"
```
