### ISSUE TITLE
Multiple Errors with Plotting

### ISSUE THREAD

**Issue by terryphi** [nschloe/tikzplotlib#303]
I'm trying to save the plot generated by the attached (in the zip file) as a tikz file.
[thermophysical_properties.zip](https://github.com/nschloe/matplotlib2tikz/files/3317378/thermophysical_properties.zip)

The plot should look like the attached pdf.
[Thermophysical.pdf](https://github.com/nschloe/matplotlib2tikz/files/3317379/Thermophysical.pdf)

I'm using the following code to insert it into a latex document (after renaming it to a .tikz file)

```
> 
 \begin{figure}
     \centering
     \input{thermophysical_plots.tikz}
     \caption{Plots thermophysical properties used in the dynamic model}
     \label{fig:thermophysical_diagram}
 \end{figure}
```

However, this is what I get:
![image](https://user-images.githubusercontent.com/25918029/59970215-5fcfd100-952e-11e9-9c62-ab490f244fac.png)

Which looks nothing like the expected output.

Note, the matplotlib .pgf exporter doesn't work for this either.

**Comment by nschloe** [comment]
Please provide a _minimal_ example of what doesn't work and paste the code here.

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to reopen at any time.
