### ISSUE TITLE
New package name

### ISSUE THREAD

**Issue by FriedrichFroebel** [nschloe/tikzplotlib#310]
It seems like this project has recently been renamed from [`matplotlib2tikz`](https://pypi.org/project/matplotlib2tikz/) to [`tikzplotlib`](https://pypi.org/project/tikzplotlib/). Both modules are available at PyPi at the moment.

What are the plans for them?

**Comment by nschloe** [comment]
Indeed. tikzplotlib is just the new name. matplotlib2tikz will continue to be available on pypi for a while, but all updates will be in tikzplotlib. Mind that tikzplotlib is Python-3-only.

**Comment by FriedrichFroebel** [comment]
Okay, it seems like my projects should be migrated to `tikzplotlib` as well. There probably should be a note about this inside the README as well.

**Comment by nschloe** [comment]
I've added a note + a warning to matplotlib2tikz on pypi; this should hopefully clarify things.

**Comment by boeddeker** [comment]
Was there a reason for this renaming?

**Comment by nschloe** [comment]
It was always tedious to type and didn't even have a good "short" name. Also, every now and then some people had interpreted the 2 as a version or association with Python 2.

**Comment by boeddeker** [comment]
Ah, ok. Thanks for the explanation.
