### ISSUE TITLE
Colours are given with too many digits for CMYK

### ISSUE THREAD

**Issue by Wrzlprmft** [nschloe/tikzplotlib#313]
Colours are defined in exports like this:
``` TeX
\definecolor{color0}{rgb}{0.941176470588235,0.501960784313725,0.501960784313725}
```

This causes `! Number too big.` when using such colours in a CMYK context, e.g., like this:

``` TeX
\documentclass{standalone}

\usepackage{xcolor}
\selectcolormodel{cmyk}
\definecolor{color0}{rgb}{0.941176470588235,0.501960784313725,0.501960784313725}

\begin{document}\end{document}
```

The reason for this is simply that the numbers have too many digits – which are irrelevant for application anyway.

**Comment by nschloe** [comment]
This looks like a bug in xcolor/cmyk. You can work around it by setting, e.g., `float_format="{:.10g}"` on `save`. I've reported this to Uwe Kern, the maintainer of xcolor.
