### ISSUE TITLE
Empty documentation on Read the Docs

### ISSUE THREAD

**Issue by FriedrichFroebel** [nschloe/tikzplotlib#315]
For some reason, the documentation at https://tikzplotlib.readthedocs.io/en/latest/ does not contain any documentation for the modules at all (the same seems to apply for https://matplotlib2tikz.readthedocs.io/en/latest/). As these docs (or at least their build status badge) are linked from the README, this does not seem to be the intended state.

**Comment by ElieGouzien** [comment]
Maybe adding something like `master_doc = 'index'` to doc/conf.py can help.

At least it allowed me to compile the doc as pdf.

**Comment by nschloe** [comment]
The error message is
```
WARNING: autodoc: failed to import module 'tikzplotlib'; the following exception was raised:
No module named 'tikzplotlib'
```
No idea why this doesn't work on readthedocs.

**Comment by nschloe** [comment]
Fixed now.
