### ISSUE TITLE
Wrong tikz code for plot with variable marker size and color

### ISSUE THREAD

**Issue by svretina** [nschloe/tikzplotlib#334]
Python3 code:
```python
fig, ax = plt.subplots()
ypred_exp = np.array(sorted(zip(x,out.best_fit)))
ax.plot(ypred_exp[:,0],ypred_exp[:,1],color="gray")
sns.scatterplot(x,y, hue=data['eos'],size=data["Mchirp"],sizes=(50,200), palette="Set2",ax=ax)
tikz.save(path+filename+".tikz")
```
Basically I want to change the colour and the size of my points according to some other variables to end up with a plot like that:
![Figure_1](https://user-images.githubusercontent.com/38790623/65436705-383d1d00-de2b-11e9-9161-3d7d887ddd49.png)

the tikz code is attached
[surface_LfM_Ltilde_fpeak_e0-fM1-2D.txt](https://github.com/nschloe/tikzplotlib/files/3642693/surface_LfM_Ltilde_fpeak_e0-fM1-2D.txt)

from line 118 to 201 the plots are empty and they should contain the same addplot command as in line 25. 
Second issue is the sectioning of the points according to colour in the different addplot commands from line 118 to 201

**Comment by nschloe** [comment]
Feel free to reopen with a minimal code example.
