### ISSUE TITLE
Reverse x axis not working

### ISSUE THREAD

**Issue by Sbozzolo** [nschloe/tikzplotlib#335]
Consider any plot in which one axis has a direction inverted to its standard configuration, for instance, an x axis that decreases going towards the right (instead of increasing).
This behavior can be achieved with matplotlib by using `xlim` with inverted extremes, like in the following MWE:

``` python
import matplotlib.pyplot as plt

plt.plot([1,2], [2,1])
plt.xlim([3,0])
```
which produces the attached figure.

`tikzplotlib` does not correctly reproduce the figure and orders the extremes in the natural way. What `tikzplotlib` should do is add: `x dir = reverse` to the axis options.

![lol](https://user-images.githubusercontent.com/9167485/65479646-20719300-de43-11e9-83a6-756b90c9eb6a.png)

**Comment by ninivert** [comment]
Can confirm, I am having the same issue. Reversing the original data array does not seem to work either.

**Comment by nschloe** [comment]
It seems that tikzplotlib _does_ do the right thing after all. It _does_ add `x dir=reverse` as you can see in the plot you posted. Everything looks exactly like the mpl figure.
![f](https://user-images.githubusercontent.com/181628/69477090-55b64500-0de2-11ea-8452-a4b5a7659f44.png)
