### ISSUE TITLE
TypeError when exporting plot with a single point

### ISSUE THREAD

**Issue by Aikhjarto** [nschloe/tikzplotlib#339]
Usually, `line.get_x_data()` as used in `tikzplotlib\line2d.py", line 21, in draw_line2d`, returns an array, even if only a single point was plotted.
However, if `line.set_data()` was used to specify plotting a single point, `line.get_xdata()` can return a int or float, for which `len` is undefined, resulting in a `TypeError`

```python
from tikzplotlib import save as tikz_save
import matplotlib.pyplot as plt

line=plt.plot(0,0,'kx')[0]
print(line.get_xdata(),type(line.get_xdata())) # is an array
tikz_save('test_single_point_plot.tikz') # works

line.set_data(1,1)
print(line.get_xdata(),type(line.get_xdata())) # is an integer
tikz_save('test_single_point_plot.tikz') # fails with TypeError: object of type 'int' has no len()```

**Comment by nschloe** [comment]
Thanks, fixed now.
