### ISSUE TITLE
colorbar.get_clim() deprecation

### ISSUE THREAD

**Issue by Aikhjarto** [nschloe/tikzplotlib#353]
As of matplotlib 3.1.0 colorbar's heritage is changed. https://matplotlib.org/api/api_changes.html#colorbarbase-inheritance

Using tikzplotlib with matplotlib>3.1.0 gives quite some deprecation warning about the functions changes around the colorbar.

A list of affected functions can be found [here](https://github.com/matplotlib/matplotlib/blob/4616f70fd1b859092fce46bf7fae7393327fab3b/lib/matplotlib/colorbar.py#L321), e.g., colorbar.get_clim() should be now colorbar.mappable.get_clim().

**Comment by nschloe** [comment]
Interesting. A PR would be much appreciated!

**Comment by Aikhjarto** [comment]
I grepped through your code and found only one call to a colorbar related deprecated function.
PR is on the way.
Code ran through circleci w/o error but I have not tested it against older versions of matplotlib.

**Comment by nschloe** [comment]
I'm totall fine with requiring a newer version. Best put that in `install_requires` in setup.py.
