### ISSUE TITLE
Run Black on master or change flake8 line length

### ISSUE THREAD

**Issue by MadsAdrian** [nschloe/tikzplotlib#356]
Working on a fix for #257 as my first contribution to tikzplotlib :) 

As flake8 is set to `max-line-length = 80` for the project, I set `line-length = 80` in Black locally. I understand from one of the commits on #348 that some code on the project is blackified. Although, several files in `/tikzplotlib` are not blackified(?), which makes for a lot of "changed lines" that are only reformatted (on save). I suggest black is run on all the files to make it easier to contribute. 

It might also be the case that the code is indeed blackified at line length 88, in which case the flake8 line length should be changed.

**Comment by nschloe** [comment]
`black . --check` gives no changes here.

**Comment by MadsAdrian** [comment]
Run at 88 lines?

**Comment by MadsAdrian** [comment]
I'll configure flake8 and black at 88 lines then. I suggest the flake8 config is changed to indicate the desired line length :)

**Comment by nschloe** [comment]
It's a bit weird that flake doesn't complain at all. The value doesn't seem to matter. But alright, change it to 88 if you want.

**Comment by MadsAdrian** [comment]
PyCodeStyle takes the flake8 config value for the project. Got lots of E501 in Atom, so I figured `80` was the desired line length as is it was set the flake8 config..
