### ISSUE TITLE
Second y-axis appears with arrow

### ISSUE THREAD

**Issue by e-dub** [nschloe/tikzplotlib#358]
I added a second axis to the right in matplotlib. This is then always shown as an arrow. 
Attached is an example exported to png from matplotlib and the output from tikzplotlib (txt instead of tex)

Any ideas for me?

![ObjConConv](https://user-images.githubusercontent.com/8830285/71309594-15aaa800-240a-11ea-8b40-021ffec3c1cb.png)

[ObjConConv.txt](https://github.com/nschloe/tikzplotlib/files/3991492/ObjConConv.txt)

**Comment by nschloe** [comment]
For reproducing, one needs a _minimal_ example _in Python_.

Also, please read in the tikz manual to see what option is missing from the tex file.

**Comment by e-dub** [comment]
Solved.  Added the following to my LaTeX preamble:

```
\pgfplotsset{ every non boxed x axis/.append style={x axis line style=-},
     every non boxed y axis/.append style={y axis line style=-}}
```
