### ISSUE TITLE
Reduce overly large datasets before saving to file

### ISSUE THREAD

**Issue by hoehnp** [nschloe/tikzplotlib#362]
First of all thank your the great work on tikz ecosystem. When using tikzplotlib for plotting large datasets I would like to avoid plotting a large number of nearly identical points. I saw that you already implemented such an algorithm in matlab2tikz with the option minimumPointsDistance. Are there any plans to implement something similar in tikzplotlib? I believe it could be highly beneficial for the usage of tikzplotlib in data science.

**Comment by nschloe** [comment]
> Are there any plans to implement something similar in tikzplotlib? 

Not by me. PRs welcome. :smile_cat:

**Comment by Aikhjarto** [comment]
this is similar to #258

**Comment by nschloe** [comment]
Yup. Closing as duplicate.
