### ISSUE TITLE
import tikzplotlib.save imports module and not function

### ISSUE THREAD

**Issue by jensheit** [nschloe/tikzplotlib#365]
I installed tikzplotlib 0.8.7 and now `import tikzplotlib.save as tikz_save` imports a module and not the function.
The reason for this seems to be the new tikzplotlib directory structure:

![image](https://user-images.githubusercontent.com/31685744/71965454-0005f280-3200-11ea-8942-f37c7eb84312.png)

Is this an expected behavior?

**Comment by nschloe** [comment]
Seems like a broken installation. `tikzplotlib.save` should always be the function.

**Comment by jensheit** [comment]
I only get this problem when using tikzplotlib>0.8.4
As soon as I install 0.8.4 again it works. I tried creating a new environment and the problem persists.
`python -c "import tikzplotlib.save as tikz_save; tikz_save('test.tex')"`
works for 0.8.4 not for 0.8.5

**Comment by nschloe** [comment]
Cannot reproduce. We can leave this issue open in case someone else stumbles upon this.

**Comment by jensheit** [comment]
I think I have found the problem.
On [pypi](https://pypi.org/project/tikzplotlib/#files) the .whl and .tar.gz files include different files.
The .whl has the same structure as shown above and leads to my error.
Using the .tar.gz file the error does not occur.

Probably some problem while building the .whl

**Comment by nschloe** [comment]
Interesting. Thanks for digging this up!

**Comment by eric-wieser** [comment]
`import tikzplotlib.save as tikz_save` will never import the function, the example code here is nonsensical - see:

```python
import fractions.Fraction as F  # fail
from fractions import Fraction as F  # ok
```
This can be closed I think

**Comment by jensheit** [comment]
Of course it can import the function. In the __init__.py save is imported from tikzplotlib.save so that 
`import tikzplotlib; tikzplotlib.save()`
works.
Otherwise it would not have worked for all previous tikzplotlib versions.

**Comment by nschloe** [comment]
The point is that
```python
import foo.bar as mybar
```
never works as you might have expected, for no package out there. You have to use
```python
from foo import bar as mybar
```
or
```
import foo
foo.bar()
```
