### ISSUE TITLE
figurewidth should maybe be renamed axiswidth

### ISSUE THREAD

**Issue by eric-wieser** [nschloe/tikzplotlib#375]
When faced with multiple subplots, `figurewidth` controls the width of each subplot, not the overall figure.

Perhaps either:
* This should be renamed to `axiswidth`
* This should be divided by the number of plots

In the past I've found myself always running with the following settings:
```python
    sep = r"1cm"
    n = len(axs)
    tikzplotlib.save("plot.tikz",
        fig,
        figurewidth=fR'\linewidth/{n} - {n-1}/{n}*{sep}',
        extra_tikzpicture_parameters={'trim axis group left', 'trim axis group right'},
        extra_axis_parameters={'scale only axis'},
        extra_groupstyle_parameters={f'horizontal sep={sep}'})
```
Perhaps a preset for these is a good idea? Unfortunately, both `scale only axis` and `trim axis ...` are needed for this division to work out - which while really useful settings, may not be an acceptable default.

**Comment by nschloe** [comment]
Let's take the easy way out and rename it to `axis_{width,height}`. It's getting a little too messy for here trying to compute the number of group columns. Just think for color bars for example or long tick labels.

I like the extra parameters, too. I'm not sure if we should add those by default if group plots are present. It'd be getting a little messy if someone explicitly _doesn't_ want those.
