### ISSUE TITLE
Refactoring as a matplotlib backend?

### ISSUE THREAD

**Issue by eric-wieser** [nschloe/tikzplotlib#380]
Instead of walking the graph ourself, would it be viable to writes `tikzplotlib` as a matlab backend? That would mean that we wouldn't need to opt-in to each new object type as it gets added, and could fall back on some semi-sane defaults (eg, `EllipseCollection` by default renders as a bunch of `Ellipses` if the backend doesn't support it directly, I think).

(Also, big thanks for this library - it produced very tidy plots for some of my reports :) )

**Comment by nschloe** [comment]
IIRC, when I first wrote the lib I wanted to make it a backend. That wasn't possible though because mpl backends can't get semantic information about the figure; no axes, colorbars, legends, etc. They just "see" primitives like lines, dots, and so on.
