### ISSUE TITLE
Installation v 0.9.0 fails?

### ISSUE THREAD

**Issue by WinMichael** [nschloe/tikzplotlib#383]
Hi,

I'm using "pip3 install tikzplotlib" and "pip3 install --upgrade tikzplotlib" to install/upgrade tikzplotlib to version 0.9.0, which seems to work since I get this version. However functions like _cleanfigure.py does not seam to be downloaded nor installed. Is there an issue in the installation protocoll?

Python version is 3.7.5.

Bests, Michael

**Comment by nschloe** [comment]
It simply isn't released yet.
