### ISSUE TITLE
clean_figure() not working

### ISSUE THREAD

**Issue by sitadrost** [nschloe/tikzplotlib#393]
Hi all,

I just discovered the clean_figure() command in tikzplotlib, and it looked like exactly what I need at the moment. Unfortunately, it seems to work only when a figure doesn't contain any points that are outside the axis limits. Example to reproduce the error (adapted from the tikzplotlib example on PyPI):
```python
import matplotlib.pyplot as plt
import numpy as np

plt.style.use("ggplot")

t = np.arange(0.0, 2.0, 0.1)
s = np.sin(2 * np.pi * t)
s2 = np.cos(2 * np.pi * t)
plt.plot(t, s, "o-", lw=4.1)
plt.plot(t, s2, "o-", lw=4.1)
plt.xlabel("time (s)")
plt.ylabel("Voltage (mV)")
plt.title("Simple plot $\\frac{\\alpha}{2}$")
plt.grid(True)

import tikzplotlib

tikzplotlib.clean_figure()
tikzplotlib.save("test.tex")
```
does work without errors, whereas this (changing ylim):
```python
import matplotlib.pyplot as plt
import numpy as np

plt.style.use("ggplot")

t = np.arange(0.0, 2.0, 0.1)
s = np.sin(2 * np.pi * t)
s2 = np.cos(2 * np.pi * t)
plt.plot(t, s, "o-", lw=4.1)
plt.plot(t, s2, "o-", lw=4.1)
plt.xlabel("time (s)")
plt.ylabel("Voltage (mV)")
plt.title("Simple plot $\\frac{\\alpha}{2}$")
plt.grid(True)
plt.ylim([-0.5, 0.5])

import tikzplotlib

tikzplotlib.clean_figure()
tikzplotlib.save("test.tex")
```
returns a `NotImplementedError`.

If it helps, I'm using tikzplotlib 0.9.1. Is there anything I can do to get this to work?

Many thanks,
Sita

**Comment by nschloe** [comment]
>  Is there anything I can do to get this to work?

Sure! Submit a PR.

**Comment by sitadrost** [comment]
By PR, do you mean pull request? I'm not much of a GitHub expert, how does a pull request work?

**Comment by nschloe** [comment]
@sitadrost Check [here](https://lmgtfy.com/?q=github+pull+request). :wink:

**Comment by sitadrost** [comment]
Alright, so by PR you did indeed meant pull request, good. Perhaps I should have phrased my question differently: of course I looked up "pull request" in the GitHub help before asking you, the explanation just didn't make much sense to me in this context. The help says: 

Pull requests let you tell others about changes you've pushed to a branch in a repository on GitHub. Once a pull request is opened, you can discuss and review the potential changes with collaborators and add follow-up commits before your changes are merged into the base branch.

So how is this supposed to help me to get clean_figure() to work? I installed tikzplotlib through conda, so my local version is not a git repository. For which branch do you want me to submit a pull request?

**Comment by nschloe** [comment]
You can of course also make your changes locally and attach them to this bug report. It's usually easier to discuss changes in PRs though, so I'd recommend you make yourself familar with GitHub. I can understand if this is quite tall of an order for you, but it is my experience with software that is in "maintenance mode" like tikzplotlib that if you don't do it yourself, no one else will do it for you.

**Comment by sitadrost** [comment]
Thanks, but I didn't make any changes, so I still don't quite see what you want me to do.

**Comment by nschloe** [comment]
I'm saying: If you want this to work sometime soon, you'll probably have to implement it yourself.

**Comment by sitadrost** [comment]
Grand, thanks for nothing, why not just say so straight off?

Never mind, I'll use some workaround.

**Comment by vthuongt** [comment]
I didnt fix the issue, but improved the error message, so that people dont need to dig to deep to fix the issue manually(i.e setting ylim/xlim appropriately)

Here is the PR
https://github.com/nschloe/tikzplotlib/pull/514
