### ISSUE TITLE
Tests failing?

### ISSUE THREAD

**Issue by ggn855** [nschloe/tikzplotlib#397]
I cloned the repo and ran `pytest`, but 54 tests failed. The most common reason was 

`TypeError: get_tikz_code() got an unexpected keyword argument 'flavor'`

Apologies if this is obvious user error on my end!

**Comment by nschloe** [comment]
I just pushed some test warning fixes. That said, I suppose your tests are falling back to the system-installed version.

**Comment by nschloe** [comment]
Closing for lack of feedback.
