### ISSUE TITLE
Issue with the hatch style option (hatch="" => hatch=None)

### ISSUE THREAD

**Issue by trixxx3** [nschloe/tikzplotlib#405]
Hello,

thanks for a help in advance. I tried your module because i wanna have clean plot in my tex later on. Installing and running of your system worked but dont know which libraries to use because Latex does not tell me which ones are missing. It might be the problem that I am new to tikz but i always think that latex packages hanbooks are not helpfull like in this case too.

Thank you
trixxx3

python code
[graph.txt](https://github.com/nschloe/tikzplotlib/files/4667494/graph.txt)
tex code
[timetable.txt](https://github.com/nschloe/tikzplotlib/files/4667487/timetable.txt)
graph
[timetable.pdf](https://github.com/nschloe/tikzplotlib/files/4667491/timetable.pdf)

**Comment by nschloe** [comment]
https://github.com/nschloe/tikzplotlib#usage

**Comment by trixxx3** [comment]
Hey nschloe,

thank you for the fast help. I copied now 

\usepackage[utf8]{inputenc}
\usepackage{pgfplots}
\DeclareUnicodeCharacter{2212}{−}
\usepgfplotslibrary{groupplots,dateplot}
\usetikzlibrary{patterns,shapes.arrows}
\pgfplotsset{compat=newest}

into my tex file and get still following error about 40 times:
>>>! Package pgf Error: Undefined pattern `None'.See the pgf package documentation for explanation.Type H <return> for immediate help.... \end{axis}

and i tried 

import tikzplotlib
tikzplotlib.Flavors.latex.preamble()
# or
tikzplotlib.Flavors.context.preamble()

as well in python with the error:
>>>AttributeError: module 'tikzplotlib' has no attribute 'Flavors'

What should i do now?

**Comment by nschloe** [comment]
You seem to be running an outdated version of tikzplotlib.

**Comment by Aikhjarto** [comment]
Tested the example with tikzplotlib 0.9.2 and it fails for me too.
Tikplotlib produces lines like
```
\draw[draw=black,fill=color0,very thin,postaction={pattern=None}] (axis cs:36,-0.375) rectangle (axis cs:36,0.375);
```
 in which `postaction={pattern=None}` is not understood by pgfplots.

**Comment by Aikhjarto** [comment]
The underlying reason seems for me in https://github.com/nschloe/tikzplotlib/blob/f07247cb19ea3cfc74299d102262e0c1850abbdb/tikzplotlib/_hatches.py#L94
where ` _MP_HATCH2PGF_PATTERN.get(hatch)` returns None if `hatch` was not part of `_MP_HATCH2PGF_PATTERN`. In the present case `hatch` being an empty string led to the error.

Seem like 'matplotlib.patches.Rectangle's get_hatch() can return an empty string now.

**Comment by Aikhjarto** [comment]
Ok, I misinterpreted something. @trixxx3  sets in line 25 of his example the hatch deliberately to an empty string. Which is not a valid hatch in terms for [matplotlib](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.patches.Patch.html#matplotlib.patches.Patch.set_hatch) but matplotlib does not complain.

**Comment by trixxx3** [comment]
Hey guys,

thank you so much guys.

@nschloe i just installed tikzplotlib via pip, so it is up-to-date.
@Aikhjarto your hint was the clue. i replaced "" by None and now it works without complains. 
Here is a comparison of the original and the tikplotlib result. Only complains is about the x axis which appears and the legend which is not placed properly. I think i can move and remove them by hand. If there is any other solution please let me know ;-)

All the best
trixxx3
matplotlib
![grafik](https://user-images.githubusercontent.com/55843043/82684612-31cda200-9c53-11ea-9197-3573861a1fe5.png)

tikz
![grafik](https://user-images.githubusercontent.com/55843043/82684510-ff23a980-9c52-11ea-8234-07dd1736765d.png)
