### ISSUE TITLE
Feature request: clean_figure() on logarithmic axes

### ISSUE THREAD

**Issue by Peiffap** [nschloe/tikzplotlib#413]
Currently, loglog plots (or regular plots, with logarithmic axes), are not allowed when calling `clean_figure()`, as they throw an exception when trying to get rid of points outside of the visible box.

It would be great if this were possible, and it should not be exceedingly hard to implement, either.

**Comment by nschloe** [comment]
Cool, go for it! I'll be happy to review the PR.

**Comment by theRealSuperMario** [comment]
Thanks for creating the issue. I think I could have a look at it over the WE, but I just want to make sure you haven't gotten started already (@Peiffap ) 

Otherwise, please point me to your code so that we can solve this efficiently together.

**Comment by Peiffap** [comment]
@theRealSuperMario You can go ahead 😊. I'd like to help but I'm quite busy for the next 2-3 weeks (but could use the feature ASAP).
