### ISSUE TITLE
trouble with log scales and clean_figure

### ISSUE THREAD

**Issue by bjuergens** [nschloe/tikzplotlib#437]
`clean_figure()` seems to break when using log-scales. 

```python3
import matplotlib.pyplot as plt
import tikzplotlib

fig, axes = plt.subplots(1)
ax = axes
ax.plot(range(1,100), range(1,100))
ax.set_yscale('log')
tikzplotlib.clean_figure()
fig.show()
```
output (console): 
```
/home/name/.venv/neuro/lib/python3.8/site-packages/tikzplotlib/_cleanfigure.py:613: RuntimeWarning: divide by zero encountered in log10
  yData = np.log10(yData)
/home/name/.venv/neuro/lib/python3.8/site-packages/tikzplotlib/_cleanfigure.py:1001: RuntimeWarning: invalid value encountered in true_divide
  v = v / np.linalg.norm(v)
```

output (image): https://i.imgur.com/n6S42ly.png

when I comment out the line `tikzplotlib.clean_figure()`, don't get any console output (as expected) and the axes are scaled correctly: https://i.imgur.com/EAsrGqM.png

**Comment by Peiffap** [comment]
Perhaps @theRealSuperMario has an idea what may be causing this.

**Comment by theRealSuperMario** [comment]
There is a fairly simple implementation: Back when the feature was requested, I only implemented log-log plots ( x AND y).

this is a semilogplot and therefore not working yet

<img width="887" alt="image" src="https://user-images.githubusercontent.com/6517465/94282659-5fec2700-ff50-11ea-866d-eed36e4e69d4.png">


Gonna fix this over the weekend, stay tuned.

**Comment by theRealSuperMario** [comment]
Sorry for the huge delay - gonna fix it today.

**Comment by theRealSuperMario** [comment]
@bjuergens @Peiffap @nschloe

**Comment by theRealSuperMario** [comment]
PR incoming

<img width="1567" alt="image" src="https://user-images.githubusercontent.com/6517465/97798587-b7ed0c00-1c27-11eb-902a-fc8e9934bcc7.png">
