### ISSUE TITLE
Scaling of labels from dufte

### ISSUE THREAD

**Issue by e-dub** [nschloe/tikzplotlib#458]
I am trying to get tikzplotlib to work with your package dufte.  And after adapting my export code originally for "regular" MatPlotLib plots, it is working well with one exception.  The labels are being scaled 0.5 and I cannot seem to figure out where this is happening in the source code.  Could you be of assistance here?

Thanks!

**Comment by nschloe** [comment]
As usual, an MWE is needed for reproducing the problem.

**Comment by e-dub** [comment]
see [dufte issue #22](https://github.com/nschloe/dufte/issues/22)

**Comment by nschloe** [comment]
I don't see an MWE there. Feel free to reopen with one if still needed.
