### ISSUE TITLE
tikzplotlib 0.9.13 falsely claims to be compatible with Python 3.6

### ISSUE THREAD

**Issue by Sbozzolo** [nschloe/tikzplotlib#526]
Because of commit f1c0c09b314810299b8a655aac69a582536f7306, `tikzplotlib 0.9.13` is not compatible with Python 3.6 (see [here for my failing CI](https://github.com/Sbozzolo/kuibit/runs/4258030802?check_suite_focus=true). However, the requirements still specify that Python 3.6 is supported (see [PyPI](https://pypi.org/project/tikzplotlib/0.9.13/)). This "breaks" the dependency solver in `poetry`. If I set that my package supports `python >= 3.6`, `poetry` will find that most updated version of `tikzplotlib` that I can use is `0.9.13`.

I don't know if it is possible to retroactively fix this. The alternative is for me to force `tikztplotlib` to version `0.9.12` when Python 3.6 is used.

**Comment by nschloe** [comment]
I'll release a new version and yank the old from pypi.

**Comment by nschloe** [comment]
I saw that 0.9.13 is already yanked.

![screenshot](https://user-images.githubusercontent.com/181628/142583680-11f2589b-3e52-455d-af79-b6d7eda81950.png)

There's nothing more I can do here. Perhaps a bug in Poetry?

**Comment by Sbozzolo** [comment]
Sorry for the noise. It is poetry that does not support yanked releases: https://github.com/python-poetry/poetry/issues/2453
