### ISSUE TITLE
opts_string for externalized tables

### ISSUE THREAD

**Issue by hgroll** [nschloe/tikzplotlib#535]
Hello,
In case the save argument "externalize_tables" is set to True, the constructed string "opts_str" is not replaced as the variable "opts_string" is expected in the f-string:
https://github.com/nschloe/tikzplotlib/blob/fe5dcf5ce3f859ee4ef28b2c066c9b8e467608a8/src/tikzplotlib/_line2d.py#L293

**Comment by 7Z0t99** [comment]
Please reopen this issue. As commented at https://github.com/nschloe/tikzplotlib/commit/1b261f4657d5a70c8fae4ca380e4607b2988db2b , the merged pull request https://github.com/nschloe/tikzplotlib/pull/539 does not fix the issue. A potential solution is also proposed at https://github.com/nschloe/tikzplotlib/commit/1b261f4657d5a70c8fae4ca380e4607b2988db2b .
