### ISSUE TITLE
Common_texification removed from matplotlib 3.8.0

### ISSUE THREAD

**Issue by dmehlem** [nschloe/tikzplotlib#593]
It seems that the method *common_texification* has been removed from matplotlib version 3.8.0. The following error occurs using matplotlib 3.8.0: `ImportError: cannot import name 'common_texification' from 'matplotlib.backends.backend_pgf'`

https://github.com/nschloe/tikzplotlib/blob/450712b4014799ec5f151f234df84335c90f4b9d/src/tikzplotlib/_axes.py#L4C3-L4C3

**Comment by nschloe** [comment]
Dup of #559.
