### ISSUE TITLE
AttributeError: module 'webcolors' has no attribute 'CSS3_HEX_TO_NAMES'

### ISSUE THREAD

**Issue by fabianabarca** [nschloe/tikzplotlib#618]
Hello,

I'm trying to run Tikzplotlib in Jupyter with Python 3.11 and I get the following error:

```bash
...
File ~/anaconda3/lib/python3.11/site-packages/tikzplotlib/_save.py:213, in get_tikz_code(figure, filepath, ...)
    [210] _print_pgfplot_libs_message(data)
    [212] # gather the file content
--> [213] data, content = _recurse(data, figure)    
    [215] # Check if there is still an open groupplot environment. This occurs if not
    [216] # all of the group plot slots are used.
...
---> [32] for h, name in webcolors.CSS3_HEX_TO_NAMES.items():
     [33]     r = int(h[1:3], 16)
     [34]     g = int(h[3:5], 16)

AttributeError: module 'webcolors' has no attribute 'CSS3_HEX_TO_NAMES'
```

I realized that this could be a compatibility problem with the `webcolors` package. I downgraded it from version 24.6 (latest available as of now) to 1.5, where the function `CSS3_HEX_TO_NAMES` [seems to exist](https://webcolors.readthedocs.io/en/1.5/contents.html#webcolors.CSS3_NAMES_TO_HEX), but still no success. Is there a workaround for this?

Also, it would be great to know what are the latest versions of the dependencies of Tikzplotlib for which it works properly (`matplotlib`, `numpy`, `Pillow`, `webcolors`), given that the development is stalled for the time being. Where can I look at that? I hope Tikzplotlib comes back to life, it's an amazing and useful tool!

**Comment by FriedrichFroebel** [comment]
The mapping is an internal API nowadays, starting at version 24.6.0: https://github.com/ubernostrum/webcolors/commit/68ba427417b6065684a162f1484c45886a401a85 Thus using `pip install "webcolors<24.6.0"` should work.

Version 1.5 works for me as well. Please ensure that you are not mixing up the version installed in your Conda environment with the one installed outside of it. And as at some point in time the package changed from a single file to a directory, you might need to uninstall the old version first to avoid conflicts.

**Comment by fabianabarca** [comment]
Thanks for the insight, makes total sense. How terrible is this for `tikzplotlib`? Will anyone installing it –starting two weeks ago– have problems with it (assuming the latest versions of all dependencies)?

Regarding the mixing up of environments, that might be my case, thanks for pointing it out.

**Comment by FriedrichFroebel** [comment]
There are known limitations with *matplotlib* already (see the other issues and PRs), requiring version < 3.6.0. For *Pillow* and *numpy*, I am not aware of any reports. And yes, this will affect users with recent *webcolors* installations as well.

**Comment by fabianabarca** [comment]
Ok, I see, problems with Matplotlib, as in Tikzplotlib. Thanks! Hoping that the project continues in the future.

**Comment by antonelloventurino** [comment]
I solved changing the code in __color.py_:
```
for h, name in webcolors.CSS3_HEX_TO_NAMES.items():
        r = int(h[1:3], 16)
        g = int(h[3:5], 16)
        b = int(h[5:7], 16)

        diff = (rgb[0] - r) ** 2 + (rgb[1] - g) ** 2 + (rgb[2] - b) ** 2
```

 as following:

```
for name in webcolors.names("css3"):
        intrgb = webcolors.name_to_rgb(name)

        diff = (rgb[0] - intrgb.red) ** 2 + (rgb[1] - intrgb.green) ** 2 + (rgb[2] - intrgb.blue) ** 2
```
